# Test your FastAPI endpoints

GET http://192.168.1.219:8000/
Accept: application/json

### Call the /search endpoint

POST http://192.168.1.219:8000/search
Content-Type: application/json

{
    "input": "Show me all the users having JavaScript skills and their Designation must be Software Engineer"
}

### Get text embeddings

POST http://192.168.1.219:8000/embed
accept: application/json
Authorization: Basic YXBpdXNlcjpraWxsYmlsbA==
Content-Type: application/json

{
  "input": "Show me all the users having JavaScript skills and their Designation must be Software Engineer"
}

###